### ISSUE TITLE
Clarify in README python-sitemapper and epa-sitemap relationship

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/sitemapper#1]
Hey! Just getting a chance to dig into your work. It is a little unclear to me right now, can you clarify @openciti ?

**Comment by openciti** [comment]
it generates site a map in xml, csv and json you can see output here https://openciti.ca/data
I was going to do a simple web interface using the json format
the other epa repo you can remove if you like

**Comment by openciti** [comment]
I've clarified the usage in the README.

**Comment by dcwalk** [comment]
The clarification is good, I meant more the relationship between this repo and https://github.com/edgi-govdata-archiving/epa-sitemap

I've marked it as 'ARCHIVED' for now, as I think this repo replaces that work. Is that accurate?

**Comment by openciti** [comment]
Exactly

**Comment by dcwalk** [comment]
Awesome! I'm closing this as addressed :)
